version: '3'

services:
  app:
    image: vusler-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./components:/app/components
      - ./utils:/app/utils
      - ./lib:/app/lib
      - ./assets:/app/assets
      - ./config:/app/config
      - ./shopify:/app/shopify
      - ./constants:/app/constants
      - ./interfaces:/app/interfaces
      - ./tsconfig.json:/app/tsconfig.json
      - ./thinkific:/app/thinkific
      - ./bold:/app/bold
      - ./cognito:/app/cognito
      - ./app:/app/app
