import { Theme } from 'theme-ui'

const theme: Theme = {
  fonts: {
    body:
      "-apple-system, system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif, BlinkMacSystemFont, 'Helvetica Neue', 'Helvetica', sans-serif",
    heading:
      "-apple-system, system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif, BlinkMacSystemFont, 'Helvetica Neue', 'Helvetica', sans-serif;",
  },
  fontWeights: {
    body: 500,
    heading: 600,
    medium: 600,
    bold: 700,
    headingBold: 800,
  },
  styles: {
    h1: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      fontStyle: 'normal',
      letterSpacing: '0.5px',
      color: 'text',
      mt: 0,
      mb: 0,
      fontSize: '35px',
    },
    h2: {
      lineHeight: 1.4,
      fontFamily: 'heading',
      fontWeight: 'medium',
      fontStyle: 'normal',
      fontSize: '25.2px',
      letterSpacing: '0.5px',
      color: 'text',
      mt: 0,
      mb: 0.2,
    },
    h3: {
      fontFamily: 'heading',
      fontWeight: 300,
      fontStyle: 'normal',
      fontSize: '19.6px',
      lineHeight: 1.3,
      mb: '0.2em',
      letterSpacing: '.4px',
    },
    h4: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      fontStyle: 'normal',
      fontSize: '14.7px',
      lineHeight: '1.1',
      letterSpacing: '3px',
      textTransform: 'uppercase',
      color: 'text',
    },
    h5: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      fontStyle: 'normal',
      fontSize: '14px',
      lineHeight: '1.6',
    },
    ul: {
      listStyleType: 'none',
      margin: '0',
      padding: '0',
    },
    ol: {
      listStyleType: 'none',
      margin: '0',
      padding: '0',
    },
    li: {
      fontFamily: 'body',
      listStyleType: 'none',
      margin: 0,
    },
    select: {
      color: 'text',
      backgroundColor: 'background',
      borderRadius: 0,
      display: 'block',
      position: 'relative',
      fontFamily: 'body',
      fontWeight: 'body',
      fontStyle: 'normal',
      fontSize: '13px',
      lineHeight: 'normal',
      border: 0,
      padding: '10px 14px',
    },
    option: {
      fontWeight: 'normal',
      display: 'block',
      whiteSpace: 'nowrap',
      minHeight: '1.2em',
      padding: '0px 2px 1px',
    },
    label: {
      letterSpacing: '0.5px',
      fontFamily: 'body',
      fontWeight: 'body',
      fontStyle: 'normal',
    },
    input: {
      color: 'text',
      backgroundColor: 'background',
      borderRadius: 0,
      display: 'block',
      position: 'relative',
      fontFamily: 'body',
      fontWeight: 'body',
      fontStyle: 'normal',
      fontSize: '13px',
      lineHeight: 'normal',
      border: 0,
      padding: '10px 14px',
    },
    p: {
      fontFamily: 'body',
      fontWeight: 'body',
      fontStyle: 'normal',
      fontSize: '13px',
      lineHeight: 1.5,
      mb: '0.618em',
      letterSpacing: '0.5px',
    },
    a: {
      fontFamily: 'body',
      fontWeight: 'body',
      fontStyle: 'normal',
      transition: '.3s',
      color: 'inherit',
      textDecoration: 'none',
      background: 'transparent',
      textShadow: '1px 1px 1px rgb(0 0 0 / 0%)',
    },
    button: {
      display: 'inline-block',
      position: 'relative',
      fontFamily: 'body',
      fontWeight: 'body',
      fontStyle: 'normal',
      transition: 'opacity .2s ease-in-out',
      cursor: 'pointer',
      padding: '10px 30px',
      margin: 'auto',
      fontSize: '1.1rem',
      lineHeight: '22px',
      textTransform: 'capitalize',
      textAlign: 'center',
      textDecoration: 'none!important',
      letterSpacing: '0.5px',
      backgroundColor: 'primary',
      color: 'background',
      border: '1px solid',
      borderColor: 'primary',
      borderRadius: 0,
    },
    img: {
      border: 0,
    },
  },
}

export default theme
