name: Deploy to ECR to DEV

on:

  push:
    branches: [ master ]

jobs:

  build:

    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 714526348732.dkr.ecr.us-east-1.amazonaws.com/lingo-fe
          IMAGE_TAG: latest
          SHOPIFY_ADMIN_API_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_ACCESS_TOKEN_DEV }}
          SHOPIFY_STOREFRONT_API_ACCESS_TOKEN: ${{ secrets.SHOPIFY_STOREFRONT_API_ACCESS_TOKEN_DEV }}
          SHOPIFY_STOREFRONT_API_KEY: ${{ secrets.SHOPIFY_STOREFRONT_API_KEY_DEV }}
          SHOPIFY_STOREFRONT_API_SECRET_KEY: ${{ secrets.SHOPIFY_STOREFRONT_API_SECRET_KEY_DEV }}
          BUILDER_PUBLIC_KEY: ${{ secrets.BUILDER_PUBLIC_KEY }}
          SHOPIFY_STORE_DOMAIN: ${{ secrets.SHOPIFY_STORE_DOMAIN_DEV }}
          STEMLINGO_API_KEY: ${{ secrets.STEMLINGO_API_KEY_DEV }}
          STEMLINGO_SUB_DOMAIN: ${{ secrets.STEMLINGO_SUB_DOMAIN_DEV }}
          BOLD_ACCESS_TOKEN: ${{ secrets.BOLD_ACCESS_TOKEN_DEV }}
          BOLD_SHARED_SECRET: ${{ secrets.BOLD_SHARED_SECRET_DEV }}
          BOLD_SHOP_IDENTIFIER: ${{ secrets.BOLD_SHOP_IDENTIFIER_DEV }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
